### ISSUE TITLE
Deprecation warning from Zustand about `equalityFn`

### ISSUE THREAD

**Issue by kjellski** [BowlingX/geschichte#139]
- **I'm submitting a ...**
  [X] bug report
  [ ] feature request
  [ ] question about the decisions made in the repository
  [ ] question about how to use this project

- **Summary**
If you install the latest versions of Geschichte and Zustand, you're getting warnings on the console that go like this:

```
[DEPRECATED] Use `createWithEqualityFn` from 'zustand/traditional'. https://github.com/pmndrs/zustand/discussions/1937
overrideMethod @ installHook.js:251
useStore @ index.mjs:9
useBoundStore @ index.mjs:30
useQuery @ store.js:66
useLicenceContractQuery @ QueryParams.ts:31
LicenceContractsView @ LicenceContractsView.tsx:19
renderWithHooks @ react-dom.development.js:16305
updateFunctionComponent @ react-dom.development.js:19595
beginWork @ react-dom.development.js:21601
beginWork$1 @ react-dom.development.js:27426
performUnitOfWork @ react-dom.development.js:26557
workLoopSync @ react-dom.development.js:26466
renderRootSync @ react-dom.development.js:26434
performConcurrentWorkOnRoot @ react-dom.development.js:25738
workLoop @ scheduler.development.js:266
flushWork @ scheduler.development.js:239
performWorkUntilDeadline @ scheduler.development.js:533
```

- **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)

Current package versions I'm using:

```
    "geschichte": "^11.1.2",
    "zustand": "^4.4.0"
```

**Comment by kjellski** [comment]
The link from above is this one:

https://github.com/pmndrs/zustand/discussions/1937

We could probably just replace the `equalityFn` as suggested.

**Comment by BowlingX** [comment]
Thank you for reporting, I will adjust the import :).
